version: "3"
services:
  frankenphp:
    build:
      context: .
      dockerfile: Dockerfile # Tambahkan baris ini
    ports:
      - "9000:8000"
    volumes:
      - .:/app
# services:
#   frankenphp:
#     build:
#       context: .
#     entrypoint: php artisan octane:frankenphp
#     ports:
#       - "9000:8000"
#     volumes:
#       - .:/app
